site_name: Sudoku AI Solver
site_url: 'https://TheNoobInventor.github.io/sudoku-ai-solver/'
use_directory_urls: False

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
repo_url: https://github.com/TheNoobInventor/sudoku-ai-solver
repo_name: TheNoobInventor/sudoku-ai-solver
plugins:
  - search:
      lang: en
