FROM ubuntu:20.04

USER root

# Update package list, upgrade system and set default locale
RUN apt update && apt upgrade -y
RUN apt install locales
RUN locale-gen en_US en_US.UTF-8
ENV LC_ALL=en_US.UTF-8 
ENV LANG=en_US.UTF-8

# Install python3 and related packages
RUN apt install python3-dev python3 python3-pip -y
RUN pip3 install --upgrade pip

# Install build tools and dependencies required by opencv
RUN apt install build-essential cmake git pkg-config libgtk-3-dev \
libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
gfortran openexr libatlas-base-dev python3-numpy libtbb2 \
libtbb-dev libdc1394-22-dev libopenexr-dev \
libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev -y

# Install OpenCV
RUN apt install libopencv-dev python3-opencv

EXPOSE 82





# Add MAINTAINER?